name: test_snowflake
description: ''
version: 0.0.1
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/airflow_job:
    name: airflow_job
    description: ''
    fabricUID: 2
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2024-05-07 15:24:15'
    author: ashish@prophecy.io
  jobs/sftp_to_snowflake_job:
    name: sftp_to_snowflake_job
    description: ''
    fabricUID: 2
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2024-05-20 09:45:03'
    author: ashish@prophecy.io
  jobs/databricks_tabluea_extract:
    name: databricks_tabluea_extract
    description: ''
    fabricUID: 2
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-05-28 14:09:18'
    author: ashish@prophecy.io
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-07 15:22:48'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/customers_by_country:
    name: customers_by_country
    schema:
      providerType: Snowflake
      fields:
      - name: COUNTRY
        dataType:
          type: String
      - name: CUSTOMERS
        dataType:
          type: Number
    description: null
    author: ashish@prophecy.io
    files:
    - models/customers_by_country.sql
    - .prophecy/ide/models/customers_by_country.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-13 08:54:55'
  .prophecy/metadata/sqlmodels/word_count:
    name: word_count
    schema:
      providerType: Snowflake
      fields:
      - name: LINE
        dataType:
          type: String
      - name: WORDS
        dataType:
          type: Array
      - name: WORDS_COUNT
        dataType:
          type: Number
    description: null
    author: ashish@prophecy.io
    files:
    - models/word_count.sql
    - .prophecy/ide/models/word_count.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-08 09:31:47'
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources:
  .prophecy/metadata/sqlsources/ASHISH_PUBLIC:
    name: ASHISH.PUBLIC
    description: null
    author: ashish@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-05-22 13:37:24'
    tables:
    - name: README
      schema:
        providerType: snowflake
        fields:
        - name: LINE
          dataType:
            type: String
      description: null
      author: ashish@prophecy.io
      createdAt: '2024-05-22 13:37:24'
  .prophecy/metadata/sqlsources/QA_DATABASE_QA_SCHEMA:
    name: QA_DATABASE.QA_SCHEMA
    description: null
    author: ashish@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-05-13 09:44:39'
    tables:
    - name: CUSTOMER_DATA
      schema:
        providerType: snowflake
        fields:
        - name: ID
          dataType:
            type: Number
        - name: NAME
          dataType:
            type: String
        - name: COMPANY
          dataType:
            type: String
        - name: EMAIL
          dataType:
            type: String
        - name: COUNTRY
          dataType:
            type: String
      description: null
      author: ashish@prophecy.io
      createdAt: '2024-05-13 09:44:39'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: ashish@prophecy.io
  createdAt: '2024-05-07 15:22:48'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
