---
version: 2
sources:
- name: "ASHISH.PUBLIC"
  database: "ASHISH"
  schema: "PUBLIC"
  config:
    enabled: true
  tables:
  - name: "README"
    columns:
    - name: "LINE"
      dataType:
        type: "String"
  - name: "CUSTOMER_DATA"
    columns:
    - name: "ID"
      dataType:
        type: "Number"
    - name: "NAME"
      dataType:
        type: "String"
    - name: "COMPANY"
      dataType:
        type: "String"
    - name: "EMAIL"
      dataType:
        type: "String"
    - name: "COUNTRY"
      dataType:
        type: "String"
