---
version: 2
sources:
- name: "QA_DATABASE.QA_SCHEMA"
  database: "QA_DATABASE"
  schema: "QA_SCHEMA"
  config:
    enabled: true
  tables:
  - name: "CUSTOMER_DATA"
    columns:
    - name: "id"
      dataType:
        type: "Number"
    - name: "name"
      dataType:
        type: "String"
    - name: "company"
      dataType:
        type: "String"
    - name: "email"
      dataType:
        type: "String"
    - name: "country"
      dataType:
        type: "String"
- name: "ASHISH.PUBLIC"
  database: "ASHISH"
  schema: "PUBLIC"
  config:
    enabled: true
  tables:
  - name: "README"
    columns:
    - name: "LINE"
      dataType:
        type: "String"
